version: '3.5'

services:
  api:
    container_name: todo.api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - MODE=debug
    ports:
      - "8080:8080"
    volumes:
      - api:/www/api
    depends_on:
      - mysql
    networks:
      - todo
  mysql:
    image: mysql:5.7
    container_name: todo.mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: root
    volumes:
      - ./data/mysql:/var/lib/mysql:rw,delegated
    networks:
      - todo
networks:
  todo:
    external: true
