name: Deploy
on:
  push:
    branches:
      - master
jobs:
  api:
    # if: contains(github.event.pull_request.labels.*.name, 'build-api')
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_build_args: |
            PACKAGE_NAME
        env:
          PACKAGE_NAME: api
