name: Unit Test
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation
      uses: actions/setup-go@v2
      with:
        go-version: 1.13.x
    - name: Check out code
      uses: actions/checkout@v2
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run tests
      run: go test -v .
